# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WtyczkaProjektGKLP
                                 A QGIS plugin
 Uzyskanie przewyższenia i pól
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-07
        copyright            : (C) 2023 by Gabriela Kaczmarek, Liliana Pijewska
        email                : liliana.pijewska.stud@pw.edu.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WtyczkaProjektGKLP class from file WtyczkaProjektGKLP.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .wtyczka_projekt_gk_lp import WtyczkaProjektGKLP
    return WtyczkaProjektGKLP(iface)
